site_name: Common Fund Data Ecosystem Training

repo_url: https://github.com/nih-cfde/training-and-engagement

theme:
  name: material
  palette:
    primary: white
  features:
    - tabs
  logo: images/CFDE-logo.png

docs_dir: docs

plugins:
  - search: # necessary for search to work
      separator: '[\s\-\.]+'
  - awesome-pages
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- codehilite:
    guess_lang: false
- toc:
    permalink: true
extra:
  hypothesis: true
extra_css:
  - stylesheets/extra.css
